server:
  port: 7080

spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account/**

        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transaction/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka